// apps/vue-demo/src/App.vue
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import type { Product, User } from "@tot/shared-types";
import { formatDate } from "@tot/shared-utils";

const API_URL = import.meta.env.VITE_API_URL;

const products = ref<Product[]>([]);
const users = ref<User[]>([]);
const search = ref("");
const loading = ref(true);
const error = ref<string | null>(null);
const newProductName = ref("");
const lastRefreshed = ref<Date | null>(null);

async function fetchData() {
  try {
    const [productsRes, usersRes] = await Promise.all([
      fetch(`${API_URL}/api/products`),
      fetch(`${API_URL}/api/users`),
    ]);
    products.value = await productsRes.json();
    users.value = await usersRes.json();
    lastRefreshed.value = new Date();
  } catch {
    error.value = "Could not reach the API. Is it running?";
  } finally {
    loading.value = false;
  }
}

function handleRefresh() {
  loading.value = true;
  error.value = null;
  fetchData();
}

async function handleAddProduct() {
  const name = newProductName.value.trim();
  if (!name) return;

  try {
    const res = await fetch(`${API_URL}/api/products`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name }),
    });
    if (!res.ok) throw new Error("Failed to add product");
    const newProduct: Product = await res.json();
    products.value.push(newProduct);
    newProductName.value = "";
  } catch {
    error.value = "Could not add product. Try again.";
  }
}

const filteredProducts = computed(() =>
  products.value.filter((p) =>
    p.name.toLowerCase().includes(search.value.toLowerCase()),
  ),
);

onMounted(fetchData);
</script>

<template>
  <div class="page">
    <div class="container">
      <div class="header">
        <div>
          <h1>tot / vue-demo</h1>
          <p class="subtitle">
            Management dashboard
            <span v-if="lastRefreshed" class="refreshed">
              · Last refreshed
              {{
                formatDate(lastRefreshed, {
                  hour: "numeric",
                  minute: "2-digit",
                })
              }}
            </span>
          </p>
        </div>
        <tot-button label="Refresh" @click="handleRefresh" />
      </div>

      <div v-if="error" class="error-card">{{ error }}</div>

      <div class="stats-grid">
        <div class="tot-card stat-card">
          <p class="stat-number">{{ loading ? "–" : products.length }}</p>
          <p class="stat-label">Products</p>
        </div>
        <div class="tot-card stat-card">
          <p class="stat-number">{{ loading ? "–" : users.length }}</p>
          <p class="stat-label">Users</p>
        </div>
      </div>

      <div class="tot-card">
        <h2>Products</h2>

        <tot-input
          placeholder="Search products..."
          :value="search"
          :onChange="(v: string) => (search = v)"
        />

        <div class="add-row">
          <tot-input
            placeholder="New product name..."
            :value="newProductName"
            :onChange="(v: string) => (newProductName = v)"
          />
          <tot-button label="Add" @click="handleAddProduct" />
        </div>

        <p v-if="loading" class="muted">Loading...</p>
        <p v-else-if="filteredProducts.length === 0" class="muted">
          No products found.
        </p>
        <table v-else>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="product in filteredProducts" :key="product.id">
              <td>{{ product.id }}</td>
              <td>{{ product.name }}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="tot-card">
        <h2>Users</h2>
        <p v-if="loading" class="muted">Loading...</p>
        <table v-else>
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(user, i) in users" :key="i">
              <td>{{ user.name }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page {
  min-height: 100vh;
  width: 100%;
  background: #f3f4f6;
  padding: 2.5rem clamp(1rem, 4vw, 4rem);
  box-sizing: border-box;
}
.container {
  max-width: 100%;
  width: 100%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
h1 {
  font-size: 1.5rem;
  font-weight: 700;
  color: #111827;
  margin: 0;
}
.subtitle {
  font-size: 0.875rem;
  color: #6b7280;
  margin: 0.25rem 0 0;
}
.refreshed {
  color: #9ca3af;
  margin-left: 0.5rem;
}
.error-card {
  border: 1px solid #fecaca;
  background: #fef2f2;
  color: #b91c1c;
  padding: 1rem;
  border-radius: 0.75rem;
}
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
}
.stat-card {
  text-align: center;
}
.stat-number {
  font-size: 1.875rem;
  font-weight: 700;
  color: #111827;
  margin: 0;
}
.stat-label {
  font-size: 0.875rem;
  color: #6b7280;
  margin: 0;
}
h2 {
  font-size: 1.125rem;
  font-weight: 600;
  color: #1f2937;
  margin: 0 0 0.75rem;
}
.add-row {
  display: flex;
  gap: 0.5rem;
  margin: 0.75rem 0 1rem;
}
.muted {
  font-size: 0.875rem;
  color: #6b7280;
}
table {
  width: 100%;
  font-size: 0.875rem;
  border-collapse: collapse;
}
th {
  text-align: left;
  padding: 0.5rem 0;
  border-bottom: 1px solid #e5e7eb;
  color: #6b7280;
}
td {
  padding: 0.5rem 0;
  border-bottom: 1px solid #f3f4f6;
  color: #374151;
}
</style>

// apps/website/src/App.tsx
import { useEffect, useState } from "react";
import { Button, Card, Input } from "@tot/ui";
import type { Product, User } from "@tot/shared-types";
import { formatDate } from "@tot/shared-utils";

const API_URL = import.meta.env.VITE_API_URL;

export default function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null);

  const fetchData = () => {
    return Promise.all([
      fetch(`${API_URL}/api/products`).then((res) => res.json()),
      fetch(`${API_URL}/api/users`).then((res) => res.json()),
    ])
      .then(([productsData, usersData]) => {
        setProducts(productsData);
        setUsers(usersData);
        setLastRefreshed(new Date());
      })
      .catch(() => setError("Could not reach the API. Is it running?"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleRefresh = () => {
    setLoading(true);
    setError(null);
    fetchData();
  };

  const filteredProducts = products.filter((p) =>
    p.name.toLowerCase().includes(search.toLowerCase()),
  );

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-10">
      <div className="mx-auto max-w-2xl space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">tot / website</h1>
            {lastRefreshed && (
              <p className="text-xs text-gray-400">
                Updated{" "}
                {formatDate(lastRefreshed, {
                  hour: "numeric",
                  minute: "2-digit",
                })}
              </p>
            )}
          </div>
          <Button onClick={handleRefresh}>Refresh</Button>
        </div>

        {error && (
          <Card className="border-red-200 bg-red-50 text-red-700">{error}</Card>
        )}

        <Card>
          <h2 className="mb-3 text-lg font-semibold text-gray-800">Products</h2>
          <Input
            placeholder="Search products..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="mb-4 w-full"
          />

          {loading ? (
            <p className="text-sm text-gray-500">Loading...</p>
          ) : filteredProducts.length === 0 ? (
            <p className="text-sm text-gray-500">No products found.</p>
          ) : (
            <ul className="space-y-2">
              {filteredProducts.map((product) => (
                <li
                  key={product.id}
                  className="flex items-center justify-between rounded-md border border-gray-100 px-3 py-2 text-sm"
                >
                  <span className="text-gray-700">{product.name}</span>
                  <span className="text-xs text-gray-400">#{product.id}</span>
                </li>
              ))}
            </ul>
          )}
        </Card>

        <Card>
          <h2 className="mb-3 text-lg font-semibold text-gray-800">Users</h2>
          {loading ? (
            <p className="text-sm text-gray-500">Loading...</p>
          ) : (
            <ul className="space-y-2">
              {users.map((user, i) => (
                <li
                  key={i}
                  className="rounded-md border border-gray-100 px-3 py-2 text-sm text-gray-700"
                >
                  {user.name}
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>
    </div>
  );
}
